plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
}

javafx {
    version = "21"
    modules = [ 'javafx.controls', 'javafx.fxml' ]
}

repositories {
    mavenCentral()
}

dependencies {
    // Yahoo Finance API
    implementation group: 'com.yahoofinance-api', name: 'YahooFinanceAPI', version: '3.17.0'

    // Konsol loglarını düzenlemek için
    implementation 'org.slf4j:slf4j-simple:2.0.9'

    // Test kütüphaneleri (Hata vermemesi için standart versiyonları yazdım)
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'org.example.Main'
}